# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0002_auto_20170630_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
