# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0003_auto_20170630_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
