# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0004_auto_20170630_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='qq',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='weiChat',
        ),
    ]
