# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0006_auto_20170630_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
