# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0008_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='qq',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, default='\u7528\u6237\u540d', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='weiChat',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
