# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0010_auto_20170701_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=255)),
                ('book_post', models.CharField(max_length=255)),
                ('book_desc', models.CharField(max_length=255)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibook.UserModel')),
            ],
        ),
    ]
