# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0011_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uid',
            new_name='user',
        ),
    ]
