# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0012_auto_20170701_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_desc',
            new_name='sbncode',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_post',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_title',
        ),
    ]
