# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0013_auto_20170703_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='uid',
        ),
    ]
