# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibook', '0019_auto_20170704_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tagStr',
            new_name='tag_str',
        ),
    ]
